/**
 * Icon — thin wrapper around react-bootstrap-icons.
 *
 * Accepts the Bootstrap Icons name with or without the "bi-" prefix:
 *   <Icon name="arrow-right" />
 *   <Icon name="bi-check-circle" className="text-green-500" size={20} />
 *
 * Only the icons actually used in this project are imported so the
 * bundler can tree-shake everything else away.
 */

import type { IconProps } from "react-bootstrap-icons";
import {
  AlarmFill,
  ArrowCounterclockwise,
  ArrowLeft,
  ArrowRepeat,
  ArrowRight,
  ArrowRightCircle,
  ArrowUpCircleFill,
  ArrowUpRight,
  Bank,
  BarChart,
  BarChartLineFill,
  Bell,
  BellFill,
  Book,
  BookHalf,
  Box,
  Briefcase,
  BugFill,
  Calendar,
  CalendarCheck,
  CalendarEventFill,
  CalendarRangeFill,
  CalendarX,
  CalendarXFill,
  Calendar2Check,
  Calendar2Plus,
  Calendar2Range,
  Calendar2Week,
  Calendar3,
  CashStack,
  ChatDots,
  ChatDotsFill,
  ChatQuote,
  ChatSquare,
  ChatSquareDots,
  ChatSquareText,
  Check,
  CheckCircle,
  CheckCircleFill,
  CheckLg,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clipboard,
  Clock,
  ClockFill,
  ClockHistory,
  Compass,
  CreditCard,
  CreditCard2FrontFill,
  CurrencyDollar,
  CursorFill,
  Download,
  DropletHalf,
  Envelope,
  EnvelopeFill,
  ExclamationCircle,
  ExclamationTriangle,
  Eye,
  EyeSlash,
  Facebook,
  FolderX,
  Gear,
  Gem,
  GeoAlt,
  GeoAltFill,
  Globe,
  GraphUp,
  GraphUpArrow,
  Grid,
  Grid3x3GapFill,
  GridFill,
  Headset,
  Heart,
  HeartFill,
  HeartPulse,
  Hospital,
  HourglassSplit,
  House,
  Images,
  Inbox,
  Instagram,
  JournalX,
  LightningCharge,
  LightningChargeFill,
  Link45deg,
  LayoutTextWindow,
  Lock,
  LockFill,
  Mortarboard,
  Palette,
  PatchCheckFill,
  Pencil,
  People,
  PeopleFill,
  Percent,
  Person,
  PersonBadge,
  PersonCheck,
  PersonCircle,
  PersonPlus,
  Phone,
  PhoneFill,
  PlayCircle,
  Plus,
  QuestionCircle,
  QuestionCircleFill,
  Receipt,
  Robot,
  RocketTakeoffFill,
  RocketTakeoff,
  Scissors,
  Search,
  Send,
  SendFill,
  Share,
  Shield,
  ShieldCheck,
  ShieldExclamation,
  ShieldFillCheck,
  ShieldLock,
  ShieldX,
  Shop,
  Sliders,
  Star,
  StarFill,
  Stars,
  Tag,
  Telephone,
  Trash,
  Type,
  VectorPen,
  Wallet2,
  Whatsapp,
  XCircle,
  XCircleFill,
  XLg,
} from "react-bootstrap-icons";

const iconMap: Record<string, React.ComponentType<IconProps>> = {
  "alarm-fill": AlarmFill,
  "arrow-counterclockwise": ArrowCounterclockwise,
  "arrow-left": ArrowLeft,
  "arrow-repeat": ArrowRepeat,
  "arrow-right": ArrowRight,
  "arrow-right-circle": ArrowRightCircle,
  "arrow-up-circle-fill": ArrowUpCircleFill,
  "arrow-up-right": ArrowUpRight,
  bank: Bank,
  "bar-chart": BarChart,
  "bar-chart-line-fill": BarChartLineFill,
  bell: Bell,
  "bell-fill": BellFill,
  book: Book,
  "book-half": BookHalf,
  box: Box,
  briefcase: Briefcase,
  "bug-fill": BugFill,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  "calendar-event-fill": CalendarEventFill,
  "calendar-range-fill": CalendarRangeFill,
  "calendar-x": CalendarX,
  "calendar-x-fill": CalendarXFill,
  "calendar2-check": Calendar2Check,
  "calendar2-plus": Calendar2Plus,
  "calendar2-range": Calendar2Range,
  "calendar2-week": Calendar2Week,
  calendar3: Calendar3,
  "cash-stack": CashStack,
  "chat-dots": ChatDots,
  "chat-dots-fill": ChatDotsFill,
  "chat-quote": ChatQuote,
  "chat-square": ChatSquare,
  "chat-square-dots": ChatSquareDots,
  "chat-square-text": ChatSquareText,
  check: Check,
  "check-circle": CheckCircle,
  "check-circle-fill": CheckCircleFill,
  "check-lg": CheckLg,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  clipboard: Clipboard,
  clock: Clock,
  "clock-fill": ClockFill,
  "clock-history": ClockHistory,
  compass: Compass,
  "credit-card": CreditCard,
  "credit-card-2-front-fill": CreditCard2FrontFill,
  "currency-dollar": CurrencyDollar,
  "cursor-fill": CursorFill,
  download: Download,
  "droplet-half": DropletHalf,
  envelope: Envelope,
  "envelope-fill": EnvelopeFill,
  "exclamation-circle": ExclamationCircle,
  "exclamation-triangle": ExclamationTriangle,
  eye: Eye,
  "eye-slash": EyeSlash,
  facebook: Facebook,
  "folder-x": FolderX,
  gear: Gear,
  gem: Gem,
  "geo-alt": GeoAlt,
  "geo-alt-fill": GeoAltFill,
  globe: Globe,
  "graph-up": GraphUp,
  "graph-up-arrow": GraphUpArrow,
  grid: Grid,
  "grid-3x3-gap-fill": Grid3x3GapFill,
  "grid-fill": GridFill,
  headset: Headset,
  heart: Heart,
  "heart-fill": HeartFill,
  "heart-pulse": HeartPulse,
  hospital: Hospital,
  "hourglass-split": HourglassSplit,
  house: House,
  images: Images,
  inbox: Inbox,
  instagram: Instagram,
  "journal-x": JournalX,
  "lightning-charge": LightningCharge,
  "lightning-charge-fill": LightningChargeFill,
  "layout-text-window": LayoutTextWindow,
  "link-45deg": Link45deg,
  lock: Lock,
  "lock-fill": LockFill,
  mortarboard: Mortarboard,
  palette: Palette,
  "patch-check-fill": PatchCheckFill,
  pencil: Pencil,
  people: People,
  "people-fill": PeopleFill,
  percent: Percent,
  person: Person,
  "person-badge": PersonBadge,
  "person-check": PersonCheck,
  "person-circle": PersonCircle,
  "person-plus": PersonPlus,
  phone: Phone,
  "phone-fill": PhoneFill,
  "play-circle": PlayCircle,
  plus: Plus,
  "question-circle": QuestionCircle,
  "question-circle-fill": QuestionCircleFill,
  receipt: Receipt,
  robot: Robot,
  "rocket-takeoff": RocketTakeoff,
  "rocket-takeoff-fill": RocketTakeoffFill,
  scissors: Scissors,
  search: Search,
  send: Send,
  "send-fill": SendFill,
  share: Share,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-exclamation": ShieldExclamation,
  "shield-fill-check": ShieldFillCheck,
  "shield-lock": ShieldLock,
  "shield-x": ShieldX,
  shop: Shop,
  sliders: Sliders,
  star: Star,
  "star-fill": StarFill,
  stars: Stars,
  tag: Tag,
  telephone: Telephone,
  trash: Trash,
  type: Type,
  "vector-pen": VectorPen,
  wallet2: Wallet2,
  whatsapp: Whatsapp,
  "x-circle": XCircle,
  "x-circle-fill": XCircleFill,
  "x-lg": XLg,
};

interface Props extends IconProps {
  name: string;
}

export function Icon({ name, className, ...props }: Props) {
  const key = name.replace(/^bi-/, "");
  const IconComponent = iconMap[key];
  if (!IconComponent) {
    if (process.env.NODE_ENV === "development") {
      console.warn(`[Icon] unknown icon: "${name}"`);
    }
    return null;
  }
  return <IconComponent className={className} {...props} />;
}
